# Generated by Django 2.2.3 on 2019-08-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
