# Generated by Django 2.2.3 on 2019-08-26 10:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20190826_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sub1', 'sub1'), ('sub2', 'sub2'), ('sub3', 'sub3'), ('sub4', 'sub4'), ('sub5', 'sub5')], max_length=1000, verbose_name='subcategories'),
        ),
    ]
