# Generated by Django 2.2.3 on 2019-08-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20190826_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
    ]
