# Generated by Django 2.2.3 on 2019-08-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0009_auto_20190826_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategories_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategories_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_fr',
        ),
    ]
