# Generated by Django 2.2.3 on 2019-08-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_auto_20190826_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
    ]
