# Generated by Django 2.2.3 on 2019-08-27 07:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20190826_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sub1', 'sub1'), ('sub2', 'sub2'), ('sub3', 'sub3'), ('sub4', 'sub4'), ('sub5', 'sub5')], max_length=1000, null=True, verbose_name='subcategories'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories_fr',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sub1', 'sub1'), ('sub2', 'sub2'), ('sub3', 'sub3'), ('sub4', 'sub4'), ('sub5', 'sub5')], max_length=1000, null=True, verbose_name='subcategories'),
        ),
    ]
