# Generated by Django 2.2.3 on 2019-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_auto_20190827_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_fr',
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
    ]
