# Generated by Django 2.2.3 on 2019-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_auto_20190827_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
