# Generated by Django 2.2.3 on 2019-08-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_auto_20190827_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
    ]
